apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: REDIS_CONNECTION
              value: redis-service
           # - name: DB_PASSWORD
           #   valueFrom:
           #     secretKeyRef:
           #       name: db-creds
           #       key: password
